services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_IS_PRODUCTION: "true"
        REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - API_BASE_URI=https://flathub.org/api/v2
    depends_on:
      - redis

  redis:
    image: docker.io/valkey/valkey:8.0-alpine
    ports:
      - "6379:6379"
